"""add batch_id to claims_master

Revision ID: a1214a06022f
Revises: ea9eb940f6be
Create Date: 2025-11-03 19:27:07.557818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1214a06022f'
down_revision: Union[str, Sequence[str], None] = 'ea9eb940f6be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims_master', sa.Column('batch_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_claims_master_batch_id'), 'claims_master', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_master_batch_id'), table_name='claims_master')
    op.drop_column('claims_master', 'batch_id')
    # ### end Alembic commands ###
