"""Initial migration - create users and claims tables

Revision ID: ea9eb940f6be
Revises: 
Create Date: 2025-11-03 03:25:56.830242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea9eb940f6be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(length=50), nullable=False),
    sa.Column('encounter_type', sa.String(length=20), nullable=True),
    sa.Column('service_date', sa.DateTime(), nullable=True),
    sa.Column('national_id', sa.String(length=20), nullable=True),
    sa.Column('member_id', sa.String(length=20), nullable=True),
    sa.Column('facility_id', sa.String(length=20), nullable=True),
    sa.Column('unique_id', sa.String(length=50), nullable=True),
    sa.Column('diagnosis_codes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('service_code', sa.String(length=20), nullable=True),
    sa.Column('paid_amount_aed', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('approval_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('error_explanation', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('technical_errors', sa.JSON(), nullable=True),
    sa.Column('medical_errors', sa.JSON(), nullable=True),
    sa.Column('data_quality_errors', sa.JSON(), nullable=True),
    sa.Column('llm_evaluated', sa.Boolean(), nullable=True),
    sa.Column('llm_confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('llm_explanation', sa.Text(), nullable=True),
    sa.Column('llm_retrieved_rules', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('rule_version', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tenant_error_type', 'claims_master', ['tenant_id', 'error_type'], unique=False)
    op.create_index('idx_tenant_status', 'claims_master', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_claims_master_claim_id'), 'claims_master', ['claim_id'], unique=True)
    op.create_index(op.f('ix_claims_master_error_type'), 'claims_master', ['error_type'], unique=False)
    op.create_index(op.f('ix_claims_master_facility_id'), 'claims_master', ['facility_id'], unique=False)
    op.create_index(op.f('ix_claims_master_id'), 'claims_master', ['id'], unique=False)
    op.create_index(op.f('ix_claims_master_service_code'), 'claims_master', ['service_code'], unique=False)
    op.create_index(op.f('ix_claims_master_status'), 'claims_master', ['status'], unique=False)
    op.create_index(op.f('ix_claims_master_tenant_id'), 'claims_master', ['tenant_id'], unique=False)
    op.create_table('rule_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('rule_type', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding_id', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_documents_tenant_id'), 'rule_documents', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('validation_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('batch_id', sa.String(length=50), nullable=True),
    sa.Column('total_claims', sa.Integer(), nullable=True),
    sa.Column('validated_claims', sa.Integer(), nullable=True),
    sa.Column('not_validated_claims', sa.Integer(), nullable=True),
    sa.Column('no_error_count', sa.Integer(), nullable=True),
    sa.Column('technical_error_count', sa.Integer(), nullable=True),
    sa.Column('medical_error_count', sa.Integer(), nullable=True),
    sa.Column('both_errors_count', sa.Integer(), nullable=True),
    sa.Column('total_paid_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('validated_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rejected_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_metrics_tenant_id'), 'validation_metrics', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_metrics_tenant_id'), table_name='validation_metrics')
    op.drop_table('validation_metrics')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rule_documents_tenant_id'), table_name='rule_documents')
    op.drop_table('rule_documents')
    op.drop_index(op.f('ix_claims_master_tenant_id'), table_name='claims_master')
    op.drop_index(op.f('ix_claims_master_status'), table_name='claims_master')
    op.drop_index(op.f('ix_claims_master_service_code'), table_name='claims_master')
    op.drop_index(op.f('ix_claims_master_id'), table_name='claims_master')
    op.drop_index(op.f('ix_claims_master_facility_id'), table_name='claims_master')
    op.drop_index(op.f('ix_claims_master_error_type'), table_name='claims_master')
    op.drop_index(op.f('ix_claims_master_claim_id'), table_name='claims_master')
    op.drop_index('idx_tenant_status', table_name='claims_master')
    op.drop_index('idx_tenant_error_type', table_name='claims_master')
    op.drop_table('claims_master')
    # ### end Alembic commands ###
